### Question 9 (Train Perceptron)

In [1]:
import itertools
import numpy as np 

In [5]:
def perceptron(X, y, max_iter = 10000):
    np.random.seed(1)
    w = np.zeros(X.shape[1])
    ctr = 0 
    for _ in range(max_iter): 
        # check which indices we make mistakes on, and pick one randomly to update 
        yXw = (y * X) @ w.T
        mistake_idxs = np.where(yXw <= 0)[0]
        if mistake_idxs.size > 0:
            ctr += 1
            i = np.random.choice(mistake_idxs) # pick idx randomly
            w = w + y[i] * X[i] # update w 
            
    return w, ctr, 'separable' if ctr < max_iter else 'not separable'

In [6]:
# (i) 
X = np.array(list(itertools.product([0, 1], repeat = 3)))
X = np.hstack((np.ones(X.shape[0]).reshape(-1, 1), X))
Y = np.array([-1, -1, 1, 1, 1, -1, -1, 1]).reshape(-1, 1) 
w, ctr, iters = perceptron(X, Y, max_iter = 100000)
w, ctr, iters

(array([-2.,  0.,  4., -1.]), 100000, 'not separable')

In [7]:
# (ii) 
X = np.array(list(itertools.product([0, 1], repeat = 3)))
X = np.hstack((np.ones(X.shape[0]).reshape(-1, 1), X))
Y = np.array([-1, -1, -1, 1, 1, 1, -1, -1]).reshape(-1, 1) 
w, ctr, iters = perceptron(X, Y, max_iter = 100000)
w, ctr, iters

(array([-2.,  0., -3.,  1.]), 100000, 'not separable')

In [8]:
# (iii) 
X = np.array(list(itertools.product([0, 1], repeat = 4)))
X = np.hstack((np.ones(X.shape[0]).reshape(-1, 1), X))
Y = np.array([-1, -1, -1, -1, 1, 1, 1, -1, 1, -1, -1, -1, 1, 1, 1, 1]).reshape(-1, 1) 
w, ctr, iters = perceptron(X, Y, max_iter = 100000)
w, ctr, iters

(array([-1.,  2.,  4., -2., -2.]), 17, 'separable')

In [10]:
# (iv) 
X = np.array(list(itertools.product([0, 1], repeat = 6)))
X = np.hstack((np.ones(X.shape[0]).reshape(-1, 1), X))
Y = -1 * np.ones(X.shape[0])
Y[0] = 1
Y[1] = 1
Y[5] = 1
Y = Y.reshape(-1, 1) 
w, ctr, iters = perceptron(X, Y, max_iter = 100000)
w, ctr, iters

(array([ 1., -4., -4., -5., -2., -5.,  2.]), 53, 'separable')